=== josemanuelponce/fullxml/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="obra"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="obra">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="año"/>
                <xs:element ref="precio"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="año" type="xs:string"/>
    <xs:element name="precio" type="xs:string"/>
</xs:schema>

=== josemanuelponce/fullxml/books.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl"?>
<?xml-stylesheet href="books.css"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/josee/OneDrive/Escritorio/xampp/htdocs/Cenec/Lenguaje%20de%20marcas/ejercicio.XML/books.xsd">
	
<obra>
  <titulo>Obra: Everyday Italian</titulo>
  <año>Año: 2005</año>
  <precio>Precio: 29.99€</precio>
</obra>

<obra>
  <titulo>Obra: Harry Potter</titulo>
  <año>Año: 2005</año>
  <precio>Precio: 29.99€</precio>
</obra>

<obra>
  <titulo>Obra: XQuery Kick Start</titulo>
  <año>Año: 2003</año>
  <precio>Precio: 49.99€</precio>
</obra>

<obra>
  <titulo lang="en">Obra: Learning XML</titulo>
  <año>Año: 2003</año>
  <precio>Precio: 39.95€</precio>
</obra>

</libro>
